# Generated by Django 5.0 on 2024-10-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='cost',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='entry_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='supplier',
        ),
        migrations.AddField(
            model_name='invoice',
            name='launch_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.supplier'),
        ),
    ]
