# Generated by Django 5.0 on 2024-11-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_supplier_remove_cost_entry_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='launch_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.typebranch'),
        ),
    ]
