# Generated by Django 5.0 on 2024-11-08 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_classification_dre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='type_id',
            new_name='type',
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typebranch',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='typebranch',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
