# Generated by Django 5.0 on 2024-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_rename_type_id_branch_type_branch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='typebranch',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
