# Generated by Django 5.0 on 2024-11-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_classification_created_at_classification_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dre',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
