# Generated by Django 5.0 on 2024-11-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0011_alter_dre_created_at_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
