# Generated by Django 5.0 on 2024-11-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0014_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_id',
            new_name='code',
        ),
    ]
