# Generated by Django 5.0 on 2024-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0015_rename_branch_id_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='period',
            field=models.CharField(max_length=7),
        ),
    ]
