# Generated by Django 5.0 on 2024-11-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0016_alter_expense_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
