# Generated by Django 5.0 on 2024-11-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0017_alter_branch_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
