# Generated by Django 5.0 on 2024-11-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0018_rename_branch_id_expense_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Expense',
            new_name='FinancialTransactions',
        ),
        migrations.RemoveField(
            model_name='dre',
            name='classification_id',
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.RemoveField(
            model_name='dre',
            name='branch_id',
        ),
        migrations.DeleteModel(
            name='LimitExpenses',
        ),
        migrations.RemoveField(
            model_name='loglimitexpenses',
            name='branch_id',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='Dre',
        ),
        migrations.DeleteModel(
            name='LogLimitExpenses',
        ),
    ]
