# Generated by Django 5.0 on 2024-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0019_financialclassification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['code'], 'verbose_name': 'filial', 'verbose_name_plural': 'filiais'},
        ),
        migrations.AlterModelOptions(
            name='financialtransactions',
            options={'ordering': ['period', 'branch'], 'verbose_name': 'transação financeira', 'verbose_name_plural': 'transações financeiras'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['launch_id'], 'verbose_name': 'nota fiscal', 'verbose_name_plural': 'notas fiscais'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['cnpj'], 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='typebranch',
            options={'ordering': ['name'], 'verbose_name': 'tipo de filial', 'verbose_name_plural': 'tipos de filiais'},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
