# Generated by Django 5.0 on 2024-12-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0020_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('typeEvent', models.CharField(max_length=30)),
                ('typeMoviment', models.CharField(max_length=30)),
                ('demonstrative', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['cod'],
            },
        ),
        migrations.CreateModel(
            name='Cooperators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('admission', models.DateField()),
                ('ocupation', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('cod', models.IntegerField(unique=True)),
                ('link', models.IntegerField(unique=True)),
                ('esocial', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=30)),
                ('demission', models.DateField(null=True)),
                ('situation', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.branch')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.DateField()),
                ('valuereference', models.FloatField()),
                ('value', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('cooperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.cooperators')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.events')),
            ],
            options={
                'verbose_name': 'histórico de evento',
                'verbose_name_plural': 'histórico de eventos',
                'ordering': ['competence', 'cooperator', 'event'],
            },
        ),
    ]
