# Generated by Django 5.0 on 2024-12-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0021_events_cooperators_eventhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperators',
            name='sex',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
