# Generated by Django 5.0 on 2024-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0022_cooperators_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperators',
            name='link',
            field=models.IntegerField(unique=True, verbose_name='Vinculo'),
        ),
    ]
