# Generated by Django 5.0 on 2024-12-03 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0023_alter_cooperators_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='typeMoviment',
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='admission',
            field=models.DateField(verbose_name='Admissão'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='birthdate',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='cod',
            field=models.IntegerField(unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='demission',
            field=models.DateField(null=True, verbose_name='Demissão'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='esocial',
            field=models.IntegerField(unique=True, verbose_name='E-Social'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='link',
            field=models.IntegerField(unique=True, verbose_name='Vínculo'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='ocupation',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='sex',
            field=models.CharField(max_length=30, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='situation',
            field=models.CharField(max_length=30, verbose_name='Sitaução Funcional'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Tipo de Contrato'),
        ),
    ]
