# Generated by Django 5.0 on 2024-12-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0025_alter_events_demonstrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperators',
            name='esocial',
            field=models.IntegerField(null=True, unique=True, verbose_name='E-Social'),
        ),
    ]
