# Generated by Django 5.0 on 2024-12-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0026_alter_cooperators_esocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperators',
            name='esocial',
        ),
    ]
