# Generated by Django 5.0 on 2024-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0027_remove_cooperators_esocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhistory',
            name='movement',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='occurrence',
            field=models.DateField(null=True),
        ),
    ]
