# Generated by Django 5.0 on 2024-12-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0029_groupevents_eventsbygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsbygroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.groupevents'),
        ),
    ]
