# Generated by Django 5.0 on 2024-12-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0030_contas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contas',
        ),
    ]
