# Generated by Django 5.0 on 2024-12-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0031_alter_eventsbygroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsbygroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.groupevents'),
        ),
    ]
