# Generated by Django 5.0 on 2024-12-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0032_alter_eventsbygroup_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cod', models.CharField(max_length=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_solicitacao', models.CharField(max_length=10)),
                ('data_solicitacao', models.DateField()),
                ('type', models.CharField(max_length=30)),
                ('qtd_itens', models.IntegerField()),
                ('justificativa', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('inicio_atendimento', models.BooleanField(default=False)),
                ('dh_inicio_atendimento', models.DateTimeField(null=True)),
                ('fim_atendimento', models.BooleanField(default=False)),
                ('dh_fim_atendimento', models.DateTimeField(null=True)),
                ('pagamento', models.BooleanField(default=False)),
                ('dh_pagamento', models.DateTimeField(null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('dh_finalizada', models.DateTimeField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('branch_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_destino', to='billings.branch')),
                ('branch_solicitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_solicitacao', to='billings.branch')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador', to='billings.operador')),
                ('operador_atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador_atendimento', to='billings.operador')),
                ('operador_fim_atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador_fim_atendimento', to='billings.operador')),
            ],
            options={
                'verbose_name': 'requisição',
                'verbose_name_plural': 'requisições',
                'ordering': ['data_solicitacao', 'branch_solicitacao', 'nr_solicitacao'],
            },
        ),
    ]
