# Generated by Django 5.0 on 2024-12-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0032_alter_eventsbygroup_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsByGroup',
        ),
    ]
