# Generated by Django 5.0 on 2024-12-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0033_operador_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='cod',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
