# Generated by Django 5.0 on 2024-12-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0033_delete_eventsbygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsByGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.events')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.groupevents')),
            ],
            options={
                'verbose_name': 'evento por grupo',
                'verbose_name_plural': 'eventos por grupos',
                'ordering': ['group', 'event'],
            },
        ),
    ]
