# Generated by Django 5.0 on 2024-12-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0034_alter_operador_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('item_id', models.CharField(max_length=30)),
                ('qtd', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.requisicao')),
            ],
            options={
                'verbose_name': 'item de requisição',
                'verbose_name_plural': 'itens de requisições',
                'ordering': ['requisicao', 'item'],
            },
        ),
    ]
