# Generated by Django 5.0 on 2024-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0036_remove_requisicao_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.CharField(default='AGUARDANDO ATENDIMENTO', max_length=50),
        ),
    ]
