# Generated by Django 5.0 on 2024-12-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0038_produtos_remove_itensrequisicao_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cod', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'classe de produto',
                'verbose_name_plural': 'classes de produtos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.classproduto'),
        ),
    ]
