# Generated by Django 5.0 on 2024-12-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0039_classproduto_produtos_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itensrequisicao',
            options={'ordering': ['requisicao', 'produto'], 'verbose_name': 'item de requisição', 'verbose_name_plural': 'itens de requisições'},
        ),
        migrations.RemoveField(
            model_name='itensrequisicao',
            name='item',
        ),
        migrations.AddField(
            model_name='itensrequisicao',
            name='dt_utiliza',
            field=models.DateField(null=True),
        ),
    ]
