# Generated by Django 5.0 on 2024-12-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0040_alter_itensrequisicao_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classproduto',
            old_name='cod',
            new_name='code',
        ),
    ]
