# Generated by Django 5.0 on 2024-12-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0041_rename_cod_classproduto_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='cod',
            new_name='code',
        ),
    ]
