# Generated by Django 5.0 on 2024-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0042_rename_cod_produtos_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='dh_aprovacao',
            field=models.DateTimeField(null=True),
        ),
    ]
