SELECT
c.NRLANCTONF, c.CDFIMOVFLPAG, fl.NMFILIAL, c.DTORIGVENPAG, f.NMRAZSOCFORN, f.NRINSJURFORN, c.CDTPCTPAGAR,
 tc.DSTPCTPAGAR, c.VRORIGPAG
FROM CONTAPAGAR c
INNER JOIN NOTAFISCAL nf ON nf.NRLANCTONF = c.NRLANCTONF AND nf.CDFILIAL = c.CDFIMOVFLPAG
INNER JOIN FORNECEDOR f ON f.CDFORNECED = nf.CDFORNECED
INNER JOIN FILIAL fl ON fl.CDFILIAL = c.CDFIMOVFLPAG
INNER JOIN TIPOCTPAGAR tc ON tc.CDTPCTPAGAR = c.CDTPCTPAGAR
WHERE c.DTORIGVENPAG BETWEEN '12/09/2024' AND '12/09/2024'