SELECT
DISTINCT(lc.NRLANCCONT) AS "NR LANCAMENTO",l.CDFILIAL AS "CR", l.CDCONTCTBL AS "CT CONTABIL", l.DTCOMPCUSTO AS "DATA CUSTO",
l.VRLANCCUST AS "VALOR", c.NMCONTCTBL, lc.DSHISTLANC
FROM LANCCCUSTO l
INNER JOIN CONTCTBL c ON c.CDCONTCTBL = l.CDCONTCTBL
INNER JOIN LANCCONT lc ON lc.NRLANCCONT = l.NRLANCCONT AND lc.CDCONTCTBL = l.CDCONTCTBL AND lc.IDTIPOLANC = 'D'
WHERE l.DTCOMPCUSTO BETWEEN '01/08/2024' AND '31/08/2024' AND l.CDCONTCTBL IN (
SELECT CDCONTCTBL FROM CONTCTBL WHERE
CDCONTCTBL LIKE '4%'
GROUP BY CDCONTCTBL HAVING LENGTH(CDCONTCTBL) = 8) AND l.CDFILIAL NOT LIKE '9999'
GROUP BY lc.NRLANCCONT,l.CDFILIAL, l.CDCONTCTBL, l.DTCOMPCUSTO, l.VRLANCCUST, c.NMCONTCTBL,lc.DSHISTLANC
ORDER BY l.CDFILIAL, l.DTCOMPCUSTO, l.CDCONTCTBL, l.VRLANCCUST


SELECT
l.CDFILIAL AS "CR", SUM(l.VRLANCCUST) AS "VALOR"
FROM LANCCCUSTO l
INNER JOIN CONTCTBL c ON c.CDCONTCTBL = l.CDCONTCTBL
INNER JOIN LANCCONT lc ON lc.NRLANCCONT = l.NRLANCCONT AND lc.CDCONTCTBL = l.CDCONTCTBL AND lc.IDTIPOLANC = 'D'
WHERE l.DTCOMPCUSTO BETWEEN '01/08/2024' AND '31/08/2024' AND l.CDCONTCTBL IN (
SELECT CDCONTCTBL FROM CONTCTBL WHERE
CDCONTCTBL LIKE '4%'
GROUP BY CDCONTCTBL HAVING LENGTH(CDCONTCTBL) = 8) AND l.CDFILIAL NOT LIKE '9999'
GROUP BY l.CDFILIAL
ORDER BY l.CDFILIAL
